name: Report a Bug
description: Create a report to help us improve.
labels: ["bug"]
body:
  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "What happened? What did you expect to happen?"
    validations:
      required: true

  - type: input
    id: browser_os
    attributes:
      label: Browser & OS
      description: What browser and operating system are you using?
      placeholder: "e.g., Chrome on Windows 11, Safari on macOS 14"
    validations:
      required: false

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: Provide step-by-step instructions to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. Observe the error
    validations:
      required: false

