authors:
  giulio:
    name: Giulio Menna
    description: Founder and maintainer of the DMMapp.
    avatar: assets/authors/giulio.jpg
  marjolein:
    name: Marjolein de Vos
    description: >-
      Co-Manager and Web-Editor at Sexy Codicology, and MA graduate of Book
      and Digital Media Studies and English Language and Culture.
    avatar: assets/authors/marjolein.jpg
